---

# module versions
rejson: 2.0.7
redistimeseries: 1.6.7
redisearch: 2.4.0
redisgraph: 2.8.8
redisbloom: 2.2.12
redisinsight: 2.0.4-preview
nodejs: v14.19.0

# common package variables
email: Redis OSS <oss@redislabs.com>
license: MIT
vendor: Redis Inc
url: "https://redis.io"

redis-stack:
  version: 0.0.1
  product: redis-stack
  summary: I am a redis stack
  description: I am a redis stack description

redis-stack-server:
  version: 0.0.1
  product: redis-stack-server
  summary: I am a redis stack server
  description: I am a redis stack server description

# note the version - no underscores or hyphens allowed
redisinsight-web:
  version: 2.0.4preview
  product: redisinsight-web
  summary: RI Web summary
  description: RI Web placeholder

# uid/gid
product_user: nobody
product_group: nobody