[tool.poetry]
name = "redis-stack-tools"
version = "0.0.1"
description = "Tools, for building redis-stack"
authors = ["Your Name <you@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
invoke = "^1.6.0"
requests = "^2.27.1"
loguru = "^0.6.0"
Jinja2 = "^3.0.3"
semantic-version = "^2.9.0"
redis = "^4.1.3"
pytest = "^7.0.0"
docker = "^5.0.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
