name: Build Redis

on: [push, pull_request]

jobs:

  build-ubuntu-bionic:
    runs-on: ubuntu-latest
    container: ubuntu:bionic
    steps:
    - uses: actions/checkout@v2
      with:
        repository: redis/redis
        path: redis
        ref: 6.2.6
    - name: install dependencies
      run: apt-get update && apt-get install -y build-essential libssl-dev
    - name: make
      run: make -C redis/src all BUILD_TLS=yes
    - name: perist redis
      uses: actions/upload-artifact@v2
      with:
        name: redis-6.2.6-bionic
        retention-days: 5
        path: |
          redis/src/redis-server
          redis/src/redis-sentinel
          redis/src/redis-check-aof
          redis/src/redis-check-rdb
          redis/src/redis-benchmark
          redis/src/redis-cli

  package:
    runs-on: ubuntu-latest
    needs: [ build-ubuntu-bionic]
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
      - name: install packaging tools
        run: |
          sudo apt-get install -y rpm unzip
      - run: gem install fpm -v 1.14.1
      - uses: actions/download-artifact@v2
        with:
          name: redis-6.2.6-bionic
          path: deps/redis-6.2.6-bionic
      - name: display structure
        run: ls -R
      - name: build the package
        run: |
          OS=Linux OSNICK=ubuntu18.04 ARCH=x86_64 REDIS_BINARIES=/usr/bin ./assemble.sh deb
      - name: perist packages
        uses: actions/upload-artifact@v2
        with:
          name: packages
          retention-days: 5
          path: |
            *.deb
            *.rpm
