name: CI

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
      - '*.md'
      - '.github/workflows/release.yml'
      - '.github/workflows/nightly-edge-docker.yml'
    branches:
      - master
      - '[0-9].[0-9]'
      - '[0-9].[0-9].[0-9]'
  pull_request:

  workflow_dispatch:

jobs:
