name: Build Redis

on: [push, pull_request]

jobs:

  build-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        redis-version: ['6.2.6']
        ubuntu-version: ['focal', 'bionic', 'xenial']
    container: ubuntu:${{matrix.ubuntu-version}}
    steps:
    - uses: actions/checkout@v2
      with:
        repository: redis/redis
        path: redis
        ref: ${{matrix.redis-version}}
    - name: install dependencies
      run: apt-get update && apt-get install -y build-essential
    - name: make
      run: make -C redis/src all test BUILD_TLS=yes
    - name: perist redis
      uses: actions/upload-artifact@v2
      with:
        name: redis-${{matrix.ubuntu-version}}-${{matrix.redis-version}}
        path: |
          redis/src/redis-server
          redis/src/redis-sentinel
          redis/src/redis-checkaof
          redis/src/redis-checkrdb
          redis/src/redis-benchmark

  build-macos-latest:
    runs-on: macos-latest
    strategy:
      matrix:
        redis-version: ['6.2.6']
    steps:
    - uses: actions/checkout@v2
      with:
        repository: redis/redis
        path: redis
        ref: ${{matrix.redis-version}}
    - name: make
      run: make -C redis/src all test BUILD_TLS=yes
    - name: perist redis
      uses: actions/upload-artifact@v2
      with:
        name: redis-osx-${{matrix.redis-version}}
        path: |
          redis/src/redis-server
          redis/src/redis-sentinel
          redis/src/redis-checkaof
          redis/src/redis-checkrdb
          redis/src/redis-benchmark

  build-centos:
    runs-on: ubuntu-latest
    container: centos:${{matrix.centos-version}}
    strategy:
      matrix:
        redis-version: ['6.2.6']
        centos-version: ['7', '8']
    steps:
    - uses: actions/checkout@v2
      with:
        repository: redis/redis
        path: redis
        ref: ${{matrix.redis-version}}
    - name: make
      run: |
        yum -y install gcc make jemalloc-devel
        make -C redis/src all test BUILD_TLS=yes
    - name: perist redis
      uses: actions/upload-artifact@v2
      with:
        name: redis-centos${{matrix.centos-version}}-${{matrix.redis-version}}
        path: |
          redis/src/redis-server
          redis/src/redis-sentinel
          redis/src/redis-checkaof
          redis/src/redis-checkrdb
          redis/src/redis-benchmark
